joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "$(arg right_prefix)gen3_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg right_prefix)joint_1
      - $(arg right_prefix)joint_2
      - $(arg right_prefix)joint_3
      - $(arg right_prefix)joint_4
      - $(arg right_prefix)joint_5
      - $(arg right_prefix)joint_6
