controller_list:
  - name: $(arg left_prefix)fake_arm_controller
    joints:
      - $(arg left_prefix)joint_1
      - $(arg left_prefix)joint_2
      - $(arg left_prefix)joint_3
      - $(arg left_prefix)joint_4
      - $(arg left_prefix)joint_5
      - $(arg left_prefix)joint_6
      - $(arg left_prefix)joint_7
      
  - name: $(arg right_prefix)fake_arm_controller
    joints:
      - $(arg right_prefix)joint_1
      - $(arg right_prefix)joint_2
      - $(arg right_prefix)joint_3
      - $(arg right_prefix)joint_4
      - $(arg right_prefix)joint_5
      - $(arg right_prefix)joint_6
