hardware_interface:
  joints:
    - $(arg left_prefix)joint_1
    - $(arg left_prefix)joint_2
    - $(arg left_prefix)joint_3
    - $(arg left_prefix)joint_4
    - $(arg left_prefix)joint_5
    - $(arg left_prefix)joint_6
    - $(arg left_prefix)joint_7
    - $(arg right_prefix)joint_1
    - $(arg right_prefix)joint_2
    - $(arg right_prefix)joint_3
    - $(arg right_prefix)joint_4
    - $(arg right_prefix)joint_5
    - $(arg right_prefix)joint_6

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
    
left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg left_prefix)joint_1
    - $(arg left_prefix)joint_2
    - $(arg left_prefix)joint_3
    - $(arg left_prefix)joint_4
    - $(arg left_prefix)joint_5
    - $(arg left_prefix)joint_6
    - $(arg left_prefix)joint_7 

right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg right_prefix)joint_1
    - $(arg right_prefix)joint_2
    - $(arg right_prefix)joint_3
    - $(arg right_prefix)joint_4
    - $(arg right_prefix)joint_5
    - $(arg right_prefix)joint_6

controller_list:
  - name: "left_gen3_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg left_prefix)joint_1
      - $(arg left_prefix)joint_2
      - $(arg left_prefix)joint_3
      - $(arg left_prefix)joint_4
      - $(arg left_prefix)joint_5
      - $(arg left_prefix)joint_6
      - $(arg left_prefix)joint_7 
      
  - name: "right_gen3_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg right_prefix)joint_1
      - $(arg right_prefix)joint_2
      - $(arg right_prefix)joint_3
      - $(arg right_prefix)joint_4
      - $(arg right_prefix)joint_5
      - $(arg right_prefix)joint_6
      
